name: PHP Coding Standards Fixer

on:
  pull_request:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.4'
          tools: composer:v2, cs2pr, phpcs, php-cs-fixer, phpstan
          
      - name: OS Version
        run: cat /etc/os-release

      - name: Install dependency nunomaduro/larastan
        run: composer require nunomaduro/larastan:^2.0 --dev
        
      - name: Install dependency vimeo/psalm 
        run: composer require --dev vimeo/psalm 
        ./vendor/bin/psalm --init   
      
      - name: Install dependency  psalm/plugin-laravel
        run: composer require --dev psalm/plugin-laravel
        ./vendor/bin/psalm-plugin enable psalm/plugin-laravel

      - name: PHP Version
        run: php -v
      
      - name: PHP CS Fixer Version
        run:  phpcs --version
      
      - name: Run phpcs
        run: phpcs -q --report=checkstyle ./app | cs2pr
  
      - name: Run PHPStan
        run: phpstan analyse
        
      - name: PHP CS Fixer Version
        run:  php-cs-fixer --version

      - name: PHP CS Fixer Run
        run: php-cs-fixer fix --diff -vvv --dry-run ./app
        
      - name: Run Psalm
        run: ./vendor/bin/psalm --output-format=github
        