name: PHP Coding Standards Fixer

on:
  pull_request:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.4'
          tools: cs2pr, phpcs, php-cs-fixer, phpstan, psalm
          
      - name: OS Version
        run: cat /etc/os-release

      - name: PHP Version
        run: php -v
      
      - name: PHP CS Fixer Version
        run:  phpcs --version
      
      - name: Run phpcs
        run: phpcs -q --report=checkstyle src | cs2pr
  
      - name: Run PHPStan
        run: phpstan analyse src
        
      - name: PHP CS Fixer Version
        run:  php-cs-fixer --version

      - name: PHP CS Fixer Run
        run: php-cs-fixer fix --diff -vvv --dry-run src
        
      - name: Run Psalm
        run: psalm --output-format=github
        